const paragraphs = [
    "In the quiet town of Hawkins, strange events unfold as kids discover a hidden world called the Upside Down. Eleven, a girl with psychokinetic powers, escapes a lab and joins the group to help find their missing friend. As the story deepens, dark creatures begin to cross into their world. Friendship and courage are tested as the kids face unknown dangers. The show mixes horror, nostalgia, and mystery, making every season more intense and emotional than the last.",
    
    "Eleven's powers aren't just cool—they're terrifying. Raised in isolation, she learns what it means to be human through friendship. Meanwhile, Hawkins is under threat from sinister government experiments and creatures like the Demogorgon. Every clue leads to another mystery. The kids, despite their age, show unmatched bravery. The bond between them is what truly holds the group together. Stranger Things captures the magic of the '80s while keeping you hooked with suspense, sci-fi, and a touch of heart.",
    
    "The Upside Down is more than a creepy alternate world—it's a reflection of fear and hidden trauma. As Hawkins gets pulled deeper into chaos, the characters grow stronger. Mike, Dustin, Lucas, and Will each have unique roles to play. Eleven's return to her roots reveals painful truths. With each season, new characters and challenges arise. Whether it's battling monsters or dealing with personal loss, Stranger Things blends supernatural horror with powerful emotional storytelling.",
    
    "The Professor isn't just a mastermind—he's a visionary. Gathering eight skilled criminals with code names like Tokyo and Berlin, he plans the biggest heist in Spain's history. Their goal is to print billions inside the Royal Mint. But things don't go as expected. Emotions, love, betrayal, and pressure from police all threaten the plan. Every moment is tense, and every decision matters. Money Heist mixes action with deep characters and sharp political commentary, making it an unforgettable series.",
    
    "With red jumpsuits and Salvador Dalí masks, the robbers in Money Heist become symbols of rebellion. Each character has a past, a motive, and something to prove. As the heist progresses, loyalty is tested. The Professor stays calm and calculated, even when chaos erupts. But no plan is perfect, and mistakes can cost lives. What started as a robbery becomes a global movement. The series challenges the system while showing the human side of every character, even the flawed ones.",
    
    "Queen of Tears tells the emotional story of a married couple facing struggles they never imagined. Hae-in, a wealthy heiress, and Hyun-woo, a simple lawyer, try to hold on as misunderstandings and illness pull them apart. But love isn't easy, especially when pride and pain stand in the way. As the truth slowly surfaces, they rediscover what brought them together. It's a tale of heartbreak, second chances, and the strength it takes to truly love someone through it all.",
    
    "In Queen of Tears, love battles time, fate, and personal wounds. When Hae-in learns of her illness, her marriage with Hyun-woo is already strained. Yet, in the face of pain, their bond begins to heal. The series paints a touching portrait of forgiveness, vulnerability, and rediscovery. Set against a backdrop of luxury and family drama, it reminds us that true love isn't flashy—it's found in the quiet moments of care, sacrifice, and standing by someone when they need it most.",
    
    "Shin Ha-ri agrees to go on a blind date pretending to be her friend, but things take a turn when the man turns out to be her boss. Business Proposal brings laughter, awkward moments, and heartwarming romance. Ha-ri tries to balance her job while hiding her identity. Meanwhile, her boss, Kang Tae-moo, begins to fall for her charm. The series plays with classic rom-com tropes, delivering strong chemistry, silly moments, and genuine emotion that keeps viewers smiling throughout.",
    
    "Business Proposal mixes office drama with hilarious romance. Ha-ri's accidental blind date with her boss sets off a chain of unexpected events. As lies pile up, so do feelings. From fake relationships to real emotions, the series explores love in the workplace with a fun twist. Kang Tae-moo's transformation from cold CEO to caring partner is both sweet and satisfying. It's a lighthearted reminder that love can be found in the most unexpected places—even during a fake date.",
    
    "Imagine Eleven joining an office where she uses telekinesis to close deals while hiding her past from the HR department. While this isn't an actual show, it's fun to mix suspense with romance and comedy. Stranger Things brings thrill and danger, while Business Proposal offers light, romantic escapism. Together, they reflect how strong storytelling—whether scary or sweet—can capture our hearts. The key is connection: characters we care about and journeys that stay with us.",
    
    "Lucifer Morningstar, the devil himself, abandons hell to live in Los Angeles, opening a nightclub and helping the LAPD solve crimes. But behind his charm lies a complex struggle between identity and redemption. As he partners with detective Chloe Decker, sparks fly, and mysteries deepen. Lucifer isn't just about crime—it's about growth, forgiveness, and finding one's true purpose. With each case, he questions his own morality, making the devil surprisingly human and endlessly entertaining to watch.",
    
    "In Lucifer, every episode blends crime, drama, and humor. Lucifer's powers—his ability to compel people to tell the truth—often lead to shocking confessions and hilarious situations. But what makes him truly fascinating is his emotional depth. As he explores love, guilt, and purpose, he realizes redemption isn't easy. His relationships, especially with Chloe and his celestial family, push him toward change. The show is smart, witty, and heartfelt, offering more than just a supernatural detective story.",
    
    "Lucifer's journey from self-indulgent ruler of hell to vulnerable, self-aware hero is what makes the series so compelling. His internal battles often mirror the crimes he investigates. Whether it's dealing with his father, God, or trying to understand humanity, Lucifer's evolution is raw and real. His charm is undeniable, but it's his growth that captures hearts. Alongside Chloe, he faces not only demons from hell, but also those within himself, making each episode meaningful and fun.",
    
    "At first glance, Lucifer is about a charming devil solving crimes. But look closer, and you'll find deep questions about free will, justice, and destiny. Chloe grounds him, reminding him of the goodness he's capable of. His friendships with Maze, Linda, and Amenadiel add warmth and humor. The celestial drama, mixed with earthly emotions, creates a perfect balance. The series shows that even the most broken beings can change if they choose to—and love plays a big role in that.",
    
    "Lucifer isn't just a show about solving murders—it's a show about solving yourself. Each character carries emotional baggage, from abandonment to guilt. Lucifer's therapy sessions with Linda reveal his most vulnerable side. His charm, jokes, and flair cover deep insecurities and longing. As he learns to trust, to love, and to forgive, viewers are reminded that even the darkest past can lead to light. It's a story of self-discovery, wrapped in wit, action, and heart."
  ];
  